FROM golang:1.22-alpine AS builder

WORKDIR /src
COPY go.mod .
COPY *.go .
COPY admin ./admin
RUN go build -trimpath -ldflags="-s -w" -o /out/ai-fast-gateway .

FROM alpine:3.20

RUN adduser -D -H app && mkdir -p /logs && chown app:app /logs
USER app

COPY --from=builder /out/ai-fast-gateway /usr/local/bin/ai-fast-gateway

ENV LISTEN_ADDR=:8317
ENV UPSTREAM_URL=http://127.0.0.1:8080
ENV LOG_FILE=/logs/ai-fast-gateway.log
ENV LOG_MAX_SIZE_MB=20
ENV LOG_MAX_BACKUPS=5
ENV LOG_ROTATE_INTERVAL_MINUTES=0
ENV MAX_IDLE_CONNS=100
ENV MAX_IDLE_CONNS_PER_HOST=100
ENV SERVICE_TIER=fast
ENV FORCE_SERVICE_TIER=false
ENV CC_WS_BRIDGE_ENABLED=false
ENV CC_WS_BRIDGE_UPSTREAM_PATH=/responses
ENV CC_WS_BRIDGE_FALLBACK_HTTP=true
ENV CC_WS_BRIDGE_DEBUG_FRAMES=false
ENV CC_WS_BRIDGE_FIRST_EVENT_TIMEOUT_MS=15000
ENV CC_WS_BRIDGE_MAX_ATTEMPTS=5
ENV CC_WS_BRIDGE_MAX_REQUEST_BYTES=0
ENV CC_WS_SESSION_ROTATE_ENABLED=false
ENV CC_WS_SESSION_ROTATE_THRESHOLD=2
ENV CC_WS_SESSION_ROTATE_STATE_FILE=
ENV OPENAI_RESPONSES_WS_BRIDGE_ENABLED=false
ENV OPENAI_RESPONSES_WS_BRIDGE_FALLBACK_HTTP=true
ENV OPENAI_RESPONSES_WS_BRIDGE_MAX_ATTEMPTS=1
ENV OPENAI_RESPONSES_WS_BRIDGE_MAX_REQUEST_BYTES=900000
ENV WS_DEBUG_PAYLOAD_BYTES=0
ENV CC_WS_POOL_MODE=client
ENV CC_WS_POOL_MAX_CONNS_PER_CLIENT=20
ENV CC_WS_POOL_MAX_IDLE_PER_CLIENT=20
ENV CC_WS_POOL_IDLE_TTL_SECONDS=600
ENV CC_WS_POOL_ACQUIRE_TIMEOUT_MS=3000
ENV ADMIN_ENABLED=false
ENV ADMIN_TOKEN=
ENV ADMIN_POLICY_STATE_FILE=
ENV TZ=Asia/Shanghai

EXPOSE 8317
ENTRYPOINT ["ai-fast-gateway"]
